"""
questions_data.py  –  Pre-loaded question bank.

Each tuple follows the schema:
    (question, option_a, option_b, option_c, option_d,
     correct_option, category, difficulty)
"""

QUESTIONS = [
    ("What planet is known as the Red Planet?", "Venus", "Mars", "Jupiter", "Saturn", "B", "Science", "Easy"),
    ("What gas do plants absorb from the atmosphere?", "Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen", "C", "Science", "Easy"),
    ("How many bones are in the adult human body?", "206", "305", "186", "256", "A", "Science", "Easy"),
    ("What is the chemical symbol for water?", "O2", "H2O", "CO2", "NaCl", "B", "Science", "Easy"),
    ("Which organ pumps blood throughout the body?", "Liver", "Lungs", "Brain", "Heart", "D", "Science", "Easy"),
    ("What is the powerhouse of the cell?", "Nucleus", "Ribosome", "Mitochondria", "Golgi Body", "C", "Science", "Hard"),
    ("What is the speed of light in vacuum (approx)?", "3 × 10⁶ m/s", "3 × 10⁸ m/s", "3 × 10¹⁰ m/s", "3 × 10⁴ m/s", "B", "Science", "Hard"),
    ("Which element has the atomic number 79?", "Silver", "Platinum", "Gold", "Copper", "C", "Science", "Hard"),
    ("What is the most abundant gas in Earth's atmosphere?", "Oxygen", "Carbon Dioxide", "Nitrogen", "Argon", "C", "Science", "Hard"),
    ("What particle has a positive charge in an atom?", "Electron", "Neutron", "Proton", "Photon", "C", "Science", "Hard"),
    ("Who was the first President of the United States?", "Abraham Lincoln", "George Washington", "Thomas Jefferson", "John Adams", "B", "History", "Easy"),
    ("In which year did World War II end?", "1942", "1943", "1944", "1945", "D", "History", "Easy"),
    ("The Taj Mahal is located in which Indian city?", "Delhi", "Jaipur", "Agra", "Mumbai", "C", "History", "Easy"),
    ("Who discovered America in 1492?", "Vasco da Gama", "Christopher Columbus", "Ferdinand Magellan", "Marco Polo", "B", "History", "Easy"),
    ("The Great Wall was built in which country?", "Japan", "India", "China", "Mongolia", "C", "History", "Easy"),
    ("Who was the first Emperor of Rome?", "Julius Caesar", "Augustus", "Nero", "Caligula", "B", "History", "Hard"),
    ("The French Revolution began in which year?", "1776", "1789", "1804", "1815", "B", "History", "Hard"),
    ("Who wrote the Communist Manifesto?", "Lenin", "Stalin", "Karl Marx", "Engels alone", "C", "History", "Hard"),
    ("The Battle of Plassey was fought in which year?", "1757", "1764", "1857", "1776", "A", "History", "Hard"),
    ("Which ancient civilization built Machu Picchu?", "Maya", "Aztec", "Inca", "Olmec", "C", "History", "Hard"),
    ("How many players are on a standard soccer team on the field?", "9", "10", "11", "12", "C", "Sports", "Easy"),
    ("In which sport is the term 'home run' used?", "Cricket", "Baseball", "Basketball", "Tennis", "B", "Sports", "Easy"),
    ("The Olympic Games are held every how many years?", "2", "3", "4", "5", "C", "Sports", "Easy"),
    ("How many points is a touchdown worth in American football?", "3", "5", "6", "7", "C", "Sports", "Easy"),
    ("Which country invented the sport of cricket?", "Australia", "India", "England", "South Africa", "C", "Sports", "Easy"),
    ("Who holds the record for most Grand Slam titles in men's tennis (as of 2024)?", "Roger Federer", "Rafael Nadal", "Novak Djokovic", "Pete Sampras", "C", "Sports", "Hard"),
    ("In which year were the first modern Olympic Games held?", "1896", "1900", "1888", "1904", "A", "Sports", "Hard"),
    ("Which country has won the most FIFA World Cups?", "Germany", "Argentina", "Brazil", "Italy", "C", "Sports", "Hard"),
    ("What is the length of a standard marathon in kilometres?", "40.195 km", "42.195 km", "44.195 km", "38.195 km", "B", "Sports", "Hard"),
    ("Who was the fastest man to run 100 m (world record)?", "Tyson Gay", "Yohan Blake", "Usain Bolt", "Carl Lewis", "C", "Sports", "Hard"),
    ("What is the capital of France?", "London", "Berlin", "Paris", "Madrid", "C", "General Knowledge", "Easy"),
    ("How many continents are there on Earth?", "5", "6", "7", "8", "C", "General Knowledge", "Easy"),
    ("Which is the largest ocean on Earth?", "Atlantic", "Indian", "Arctic", "Pacific", "D", "General Knowledge", "Easy"),
    ("What colour do you get when you mix red and white?", "Orange", "Pink", "Purple", "Peach", "B", "General Knowledge", "Easy"),
    ("How many days are there in a leap year?", "364", "365", "366", "367", "C", "General Knowledge", "Easy"),
    ("What is the smallest country in the world by area?", "Monaco", "Vatican City", "San Marino", "Liechtenstein", "B", "General Knowledge", "Hard"),
    ("Which language has the most native speakers worldwide?", "English", "Hindi", "Spanish", "Mandarin Chinese", "D", "General Knowledge", "Hard"),
    ("What is the hardest natural substance on Earth?", "Gold", "Iron", "Diamond", "Platinum", "C", "General Knowledge", "Hard"),
    ("Who painted the Mona Lisa?", "Michelangelo", "Raphael", "Leonardo da Vinci", "Donatello", "C", "General Knowledge", "Hard"),
    ("What is the currency of Japan?", "Yuan", "Won", "Yen", "Ringgit", "C", "General Knowledge", "Hard"),
    ("What does the letter 'S' stand for in 'NASA'?", "Space", "Star", "Science", "Society", "A", "Science", "Easy"),
    ("How many bones are in the human body?", "203", "200", "206", "209", "C", "Science", "Easy"),
    ("Who discovered the Law of Gravity?", "Galileo Galilei", "Albert Einstein", "Sir Isaac Newton", "Charles Darwin", "C", "Science", "Easy"),
    ("What is the standard SI unit for temperature?", "Fahrenheit", "Celsius", "Kelvin", "Rankine", "C", "Science", "Easy"),
    ("What is the atomic mass of Carbon?", "12", "14", "10", "16", "A", "Science", "Easy"),
    ("The biggest distinction between a eukaryotic cell and a prokaryotic cell is:", "The overall size", "The mode of reproduction", "The presence or absence of certain organelles", "The presence or absence of a nucleus", "D", "Science", "Easy"),
    ("Which of the following is not one of the groups on the periodic table?", "Halogens", "Fluorines", "Noble Gases", "Alkali Metals", "B", "Science", "Easy"),
    ("How many planets are there in the Solar System?", "8", "9", "11", "10", "A", "Science", "Easy"),
    ("What is the powerhouse of the cell?", "Redbull", "Mitochondria", "Ribosome", "Nucleus", "B", "Science", "Easy"),
    ("About what percentage of the Earth's surface is water? ", "30%", "90%", "50%", "70%", "D", "Science", "Easy"),
    ("What animal takes part in Schrödinger's most famous thought experiment?", "Dog", "Butterfly", "Cat", "Bat", "C", "Science", "Easy"),
    ("Which gas forms about 78% of the Earth’s atmosphere?", "Oxygen", "Argon", "Carbon Dioxide", "Nitrogen", "D", "Science", "Easy"),
    ("What did Gregory Mendel use to test genetic crossovers?", "Parrots", "Cats", "Peas", "Flowers", "C", "Science", "Easy"),
    ("The human heart has how many chambers?", "6", "2", "3", "4", "D", "Science", "Easy"),
    ("What lies at the center of our galaxy?", "A quasar", "A supernova", "A black hole", "A wormhole", "C", "Science", "Easy"),
    ("Which is the most abundant element in the universe?", "Helium", "Lithium", "Oxygen", "Hydrogen", "D", "Science", "Easy"),
    ("How many laws of thermodynamics are there?", "Two", "Three", "Four", "Five", "C", "Science", "Easy"),
    ("What is the largest planet in the Solar System?", "Earth", "Jupiter", "Mars", "Saturn", "B", "Science", "Easy"),
    ("How many planets are in our Solar System?", "Nine", "Seven", "Ten", "Eight", "D", "Science", "Easy"),
    ("What is the unit of electrical resistance?", "Tesla", "Joule", "Mho", "Ohm", "D", "Science", "Easy"),
    ("Which of these bones is hardest to break?", "Femur", "Humerus", "Cranium", "Tibia", "A", "Science", "Easy"),
    ("Stars consist mainly of hydrogen and which other gas?", "Oxygen", "Helium", "Argon", "Nitrogen", "B", "Science", "Easy"),
    ("What was the name of the first artificial Earth satellite, launched by the Soviet Union in 1957?", "Sputnik 1", "Soyuz 7K-OK", "Voskhod 3KV", "Zenit-2", "A", "Science", "Easy"),
    ("What is the hottest planet in the solar system", "Jupiter", "Mars", "Venus", "Mercury ", "C", "Science", "Easy"),
    ("What is the primary addictive substance found in tobacco?", "Ephedrine", "Cathinone", "Nicotine", "Glaucine", "C", "Science", "Easy"),
    ("Which programming language shares its name with an island in Indonesia?", "Jakarta", "Java", "Python", "C", "B", "Science", "Easy"),
    ("What does LTS stand for in the software market?", "Long Taco Service", "Ludicrous Transfer Speed", "Long Term Support", "Ludicrous Turbo Speed", "C", "Science", "Easy"),
    ("When Gmail first launched, how much storage did it provide for your email?", "5GB", "1GB", "Unlimited", "512MB", "B", "Science", "Easy"),
    ("If you were to code software in this language you'd only be able to type 0's and 1's.", "Binary", "Python", "C++", "JavaScript", "A", "Science", "Easy"),
    ("What is the code name for the mobile operating system Android 7.0?", "Ice Cream Sandwich", "Nougat", "Jelly Bean", "Marshmallow", "B", "Science", "Easy"),
    ("What does the computer software acronym JVM stand for?", "Java Vendor Machine", "Java Visual Machine", "Just Virtual Machine", "Java Virtual Machine", "D", "Science", "Easy"),
    ("The numbering system with a radix of 16 is more commonly referred to as ", "Duodecimal", "Binary", "Octal", "Hexidecimal", "D", "Science", "Easy"),
    ("The programming language 'Swift' was created to replace what other programming language?", "C++", "C#", "Objective-C", "Ruby", "C", "Science", "Easy"),
    ("In \"Hexadecimal\", what color would be displayed from the color code? \"#00FF00\"?", "Blue", "Red", "Yellow", "Green", "D", "Science", "Easy"),
    ("In computing, what does MIDI stand for?", "Musical Instrument Digital Interface", "Modular Interface of Digital Instruments", "Musical Interface of Digital Instruments", "Musical Instrument Data Interface", "A", "Science", "Easy"),
    ("How long is an IPv6 address?", "128 bytes", "32 bits", "128 bits", "64 bits", "C", "Science", "Easy"),
    ("How many bits are commonly in a single byte?", "Eight bits", "Twelve bits", " Fifteen bits", "Six bits", "A", "Science", "Easy"),
    ("The series of the Intel HD graphics generation succeeding that of the 5000 and 6000 series (Broadwell) is called:", "HD Graphics 7000", "HD Graphics 500", "HD Graphics 700 ", "HD Graphics 600", "B", "Science", "Easy"),
    ("Which computer language would you associate Django framework with?", "C#", "Python", "Java", "C++", "B", "Science", "Easy"),
    ("In web design, what does CSS stand for?", "Corrective Style Sheet", "Counter Strike: Source", "Computer Style Sheet", "Cascading Style Sheet", "D", "Science", "Easy"),
    ("What does the term USB stand for?", "Universal Simtex Blot", "Unified Signal Bus", "Unityped Semtex Backer", "Universal Serial Bus", "D", "Science", "Easy"),
    ("What does the \"MP\" stand for in MP3?", "Multi Pass", "Music Player", "Moving Picture", "Micro Point", "C", "Science", "Easy"),
    ("Which company was established on April 1st, 1976 by Steve Jobs, Steve Wozniak and Ronald Wayne?", "Atari", "Microsoft", "Commodore", "Apple", "D", "Science", "Easy"),
    ("HTML is what type of language?", "Scripting Language", "Macro Language", "Programming Language", "Markup Language", "D", "Science", "Easy"),
    ("According to the International System of Units, how many bytes are in a kilobyte of RAM?", "500", "1024", "512", "1000", "D", "Science", "Easy"),
    ("In computing, what does LAN stand for?", "Long Antenna Node", "Land Address Navigation", "Light Access Node", "Local Area Network", "D", "Science", "Easy"),
    ("The Electron computer was released in Britain during 1983 for the home computing market, by which company? ", "Commodore Business Machines", "Sinclair Research", "Acorn Computers", "Amstrad PLC", "C", "Science", "Easy"),
    ("What does CPU stand for?", "Central Processing Unit", "Central Process Unit", "Computer Personal Unit", "Central Processor Unit", "A", "Science", "Easy"),
    ("On Twitter, what was the original character limit for a Tweet?", "140", "100", "160", "120", "A", "Science", "Easy"),
    ("Which SQL keyword is used to fetch data from a database?", "INDEX", "VALUES", "EXEC", "SELECT", "D", "Science", "Easy"),
    ("Which of the following liquids is least viscous? Assume temperature is 25°C.", "Water", "Mercury", "Benzene", "Acetone", "D", "Science", "Hard"),
    ("Botanically speaking, which of these fruits is NOT a berry?", "Concord Grape", "Blueberry", "Strawberry", "Banana", "C", "Science", "Hard"),
    ("On the Beaufort Scale of wind force, what wind name is given to number 8?", "Hurricane", "Storm", "Gale", "Breeze", "C", "Science", "Hard"),
    ("What is the scientific name of the red fox?", "Vulpes Redus", "Red Fox", "Vulpes Vulpes", "Vulpes Vulpie", "C", "Science", "Hard"),
    ("Which constellation contains the center of the Milky Way?", "Capricornus", "Ophiuchus", "Scorpius", "Sagittarius", "D", "Science", "Hard"),
    ("What is the same in Celsius and Fahrenheit?", "32", "-39", "-40", "-42", "C", "Science", "Hard"),
    ("What physics principle relates the net electric flux out of a closed surface to the charge enclosed by that surface?", "Ampere's Law", "Gauss's Law", "Faraday's Law", "Biot-Savart Law", "B", "Science", "Hard"),
    ("Burning which of these metals will produce a bright white flame?", "Magnesium", "Lithium", "Copper", "Lead", "A", "Science", "Hard"),
    ("How many protons are in an oxygen atom?", "Six", "Two", "Four", "Eight", "D", "Science", "Hard"),
    ("What is the unit of electrical inductance?", "Henry", "Mho", "Coulomb", "Weber", "A", "Science", "Hard"),
    ("Which of the following is the term for \"surgical complications resulting from surgical sponges left inside the patient's body?", "Meupareunia", "Jentacular", "Gongoozler", "Gossypiboma", "D", "Science", "Hard"),
    ("What is the molecular formula of Ozone?", "N2O", "C6H2O6", "O3", "SO4", "C", "Science", "Hard"),
    ("What common name is given to the medial condition, tibial stress syndrome (MTSS)?", "Tennis Elbow", "Housemaid's Knee", "Shin Splints", "Carpal Tunnel", "C", "Science", "Hard"),
    ("Which of these animals belongs in class Chondrichthyes?", "Killer whale", "Catfish", "Octopus", "Great white shark", "D", "Science", "Hard"),
    ("Which of the following is NOT a real element?", "Praseodymium", "Vitrainium", "Hassium", "Lutetium", "B", "Science", "Hard"),
    ("A comet's gaseous envelope (which creates the tail) is called what?", "The coma", "The backwash", "The ablative", "The wake", "A", "Science", "Hard"),
    ("What was the first organic compound to be synthesized from inorganic compounds?", "Urea", "Ethanol", "Formaldehyde", "Propane", "A", "Science", "Hard"),
    ("What is the standard SI unit for luminous intensity?", "Candela", "Lumen", "Faraday", "Coulomb", "A", "Science", "Hard"),
    ("The core of the Sun can reach which temperature?", "27° Million F (15° Million C)", "8° Billion F (°4.4 Billion C)", "Absolute Zero (Both F and C)", "938,000° F (521093.3° C)", "A", "Science", "Hard"),
    ("Which one of these is scientific term for \"Brain Freeze\"?", "Hyacinthoides Italica", "Amaranthus Retroflexus", "Amblyomma Americanum", "Sphenopalatine Ganglioneuralgia", "D", "Science", "Hard"),
    ("Muscle fiber is constructed of bundles small long organelles called what?", "Epimysium", "Myocardium", "Myofiaments", "Myofibrils", "D", "Science", "Hard"),
    ("Folic acid is the synthetic form of which vitamin?", "Vitamin D", "Vitamin B", "Vitamin C", "Vitamin A", "B", "Science", "Hard"),
    ("Which of the following is a major muscle of the back?", "Trapezoid", "Trapezius", "Trapezium", "Triquetrum", "B", "Science", "Hard"),
    ("In quantum physics, which of these theorised sub-atomic particles has yet to be observed?", "Z boson", "Tau neutrino", "Graviton", "Gluon", "C", "Science", "Hard"),
    ("What is isobutylphenylpropanoic acid more commonly known as?", "Ketamine", "Aspirin", "Morphine", "Ibuprofen", "D", "Science", "Hard"),
    ("What was the name of the security vulnerability found in Bash in 2014?", "Heartbleed", "Stagefright", "Bashbug", "Shellshock", "D", "Science", "Hard"),
    ("Which of these Cherry MX mechanical keyboard switches is both tactile and clicky?", "Cherry MX Blue", "Cherry MX Black", "Cherry MX Red", "Cherry MX Brown", "A", "Science", "Hard"),
    ("What major programming language does Unreal Engine 4 use?", "C#", "Assembly", "C++", "ECMAScript", "C", "Science", "Hard"),
    ("What was the name of the first Bulgarian personal computer?", "Pravetz 8D", "IZOT 1030", "Pravetz 82", "IMKO-1", "D", "Science", "Hard"),
    ("Which of the following computer components can be built using only NAND gates?", "ALU", "CPU", "Register", "RAM", "A", "Science", "Hard"),
    ("CMOS is tech used for constructing integrated circuits. What does CMOS stand for?", "Computer-made oscillating static", "Computer-made operating system", "Complementary magnetic-ohms-semiconductor", "Complementary metal–oxide–semiconductor", "D", "Science", "Hard"),
    ("What was the first company to use the term \"Golden Master\"?", "Google", "Apple", "IBM", "Microsoft", "B", "Science", "Hard"),
    ("Which of these names was an actual codename for a cancelled Microsoft project?", "Saturn", "Neptune", "Enceladus", "Pollux", "B", "Science", "Hard"),
    ("Which of the following physical typologies are used with Ethernet Networks?", "Hex", "Star", "Mesh", "Ring", "B", "Science", "Hard"),
    ("What vulnerability ranked #1 on the OWASP Top 10 in 2013?", "Broken Authentication", "Insecure Direct Object References", "Cross-Site Scripting", "Injection ", "D", "Science", "Hard"),
    ("Which of the following is NOT a computer science algorithm?", "Float Sort", "Quick Sort", "Merge Sort", "Bubble Sort", "A", "Science", "Hard"),
    ("What is the codename of the eighth generation Intel Core micro-architecture launched in October 2017?", "Skylake", "Coffee Lake", "Sandy Bridge", "Broadwell", "B", "Science", "Hard"),
    ("Lenovo acquired IBM's personal computer division, including the ThinkPad line of laptops and tablets, in what year?", "2002", "1999", "2008", "2005", "D", "Science", "Hard"),
    ("Australia, Japan, and Southeast Asia are in which ITU Region?", "Region 1", "Region 2", "Region 4", "Region 3", "D", "Science", "Hard"),
    ("Which data structure does FILO apply to?", "Stack", "Tree", "Heap", "Queue", "A", "Science", "Hard"),
    ("Dutch computer scientist Mark Overmars is known for creating which game development engine?", "Torque 2D", "Game Maker", "Construct", "Stencyl", "B", "Science", "Hard"),
    ("What type of sound chip does the Super Nintendo Entertainment System (SNES) have?", "ADPCM Sampler", "Programmable Sound Generator (PSG)", "PCM Sampler", "FM Synthesizer", "A", "Science", "Hard"),
    ("What internet protocol was documented in RFC 1459?", "IRC", "HTTP", "FTP", "HTTPS", "A", "Science", "Hard"),
    ("According to DeMorgan's Theorem, the Boolean expression (AB)' is equivalent to:", "A' + B'", "A'B'", "AB' + AB", "A'B + B'A", "A", "Science", "Hard"),
    ("Who invented the \"Spanning Tree Protocol\"?", "Vint Cerf", "Michael Roberts", "Paul Vixie", "Radia Perlman", "D", "Science", "Hard"),
    ("Which of these was the name of a bug found in April 2014 in the publicly available OpenSSL cryptography library?", "Shellscript", "Shellshock", "Corrupted Blood", "Heartbleed", "D", "Science", "Hard"),
    ("The acronym \"RIP\" stands for which of these?", "Routing Information Protocol", "Runtime Instance Processes", "Regular Interval Processes", "Routine Inspection Protocol", "A", "Science", "Hard"),
    ("What is the name of the process that sends one qubit of information using two bits of classical information?", "Quantum Entanglement", "Quantum Teleportation", "Super Dense Coding", "Quantum Programming", "B", "Science", "Hard"),
    ("What does the International System of Quantities refer 1024 bytes as?", "Kelobyte", "Kylobyte", "Kilobyte", "Kibibyte", "D", "Science", "Hard"),
    ("What port does HTTP run on?", "443", "53", "80", "23", "C", "Science", "Hard"),
    ("The original Roman alphabet lacked the following letters EXCEPT:", "X", "J", "U", "W", "A", "History", "Easy"),
    ("Who led the Communist Revolution of Russia?", "Joseph Stalin", "Mikhail Gorbachev", "Vladimir Lenin", "Vladimir Putin", "C", "History", "Easy"),
    ("The RMS Titanic sunk during her maiden voyage from Southampton, England to which American city?", "Philadelphia", "Washington", "New York City", "Boston ", "C", "History", "Easy"),
    ("What country joined the EU in 2013?", "Croatia", "Bulgaria", "Turkey", "Slovenia", "A", "History", "Easy"),
    ("Who was the Confederate general in the American Civil War?", "Ulysses S. Grant", "Robert E. Lee", "George B. McClellan", "George A. Custer", "B", "History", "Easy"),
    ("Who was the first prime minister of Canada?", "John Macdonald", "John Abbott", "Robert Borden", "Alexander Mackenzie", "A", "History", "Easy"),
    ("Which of these countries remained neutral during World War II?", "United Kingdom", "France", "Switzerland", "Italy", "C", "History", "Easy"),
    ("In which war did the atomic bombings of Hiroshima and Nagasaki occur?", "Russo-Japanese War", "World War II", "First Sino-Japanese War", "World War I", "B", "History", "Easy"),
    ("What was the first sport to have been played on the moon?", "Tennis", "Football", "Soccer", "Golf", "D", "History", "Easy"),
    ("In what year was the M1911 pistol designed?", "1907", "1917", "1899", "1911", "D", "History", "Easy"),
    ("King Henry VIII was the second monarch of which European royal house?", "Stuart", "York", "Lancaster", "Tudor", "D", "History", "Easy"),
    ("In 1720, England was in massive debt and became involved in the South Sea Bubble. Who was the main mastermind behind it?", "John Churchill", "John Blunt", "Robert Harley", "Daniel Defoe", "B", "History", "Easy"),
    ("What was Manfred von Richthofen's nickname?", "The High Flying Ace", "The Red Baron", "The Blue Serpent ", "The Germany Gunner", "B", "History", "Easy"),
    ("Who was the first president of the United States?", "James Madison", "Thomas Jefferson", "James K. Polk", "George Washington", "D", "History", "Easy"),
    ("Which German field marshal was known as the `Desert Fox`?", "Ernst Busch", "Wolfram Freiherr von Richthofen", "Erwin Rommel", "Wilhelm List", "C", "History", "Easy"),
    ("The Ottoman Empire was dissolved after their loss in which war?", "World War I", "Serbian Revolution", "Second Balkan War", "Crimean War", "A", "History", "Easy"),
    ("In what year did the Great Northern War, between Russia and Sweden, end?", "1724", "1727", "1721", "1726", "C", "History", "Easy"),
    ("Who was the Prime Minister of Japan when Japan declared war on the US?", "Isoroku Yamamoto", "Fumimaro Konoe", "Michinomiya Hirohito", "Hideki Tojo", "D", "History", "Easy"),
    ("In 1453, which important city fell?", "Athens", "Constantinople", "Hamburg", "Rome", "B", "History", "Easy"),
    ("Which famous world leader is famed for the saying, \"Let them eat cake\", yet is rumored that he/she never said it at all?", "Elizabeth I", "Henry VIII", "Marie Antoinette", "Czar Nicholas II", "C", "History", "Easy"),
    ("Which modern country is known as \"The Graveyard of Empires\"?", "Russia", "Afghanistan", "China", "Iraq", "B", "History", "Easy"),
    ("Who was among those killed in the 2010 Smolensk, Russia plane crash tragedy?", "The Polish President", "Bang-Ding Ow", "Pope John Paul II", "Albert Putin", "A", "History", "Easy"),
    ("Which famous military commander marched an army, which included war elephants, over the Alps during the Second Punic War?", "Tiberius", "Garmanicus", "Alexander the Great", "Hannibal", "D", "History", "Easy"),
    ("Pol Pot was the former dictator of which country?", "Laos", "Vietnam", "Cambodia", "North Korea", "C", "History", "Easy"),
    ("When was Google founded?", "Feburary 7th, 2000", "October 9, 1997", "September 4, 1998", "December 12, 1989", "C", "History", "Easy"),
    ("Who was the first American in space?", "John Glenn", "Jim Lovell", "Alan Shephard", "Neil Armstrong", "C", "History", "Easy"),
    ("Which of the following countries was not an axis power during World War II?", "Germany", "Japan", " Soviet Union", "Italy", "C", "History", "Easy"),
    ("Which of the following was Brazil was a former colony under?", "France", "The Netherlands", "Spain", "Portugal", "D", "History", "Easy"),
    ("Which one of these was not a beach landing site in the Invasion of Normandy?", "Juno", "Gold", "Sword", "Silver", "D", "History", "Easy"),
    ("Which of the following African countries was most successful in resisting colonization?", "Congo", "Namibia", "Ethiopia", "Côte d’Ivoire", "C", "History", "Easy"),
    ("How many manned moon landings have there been?", "7", "1", "3", "6", "D", "History", "Easy"),
    ("The \"Trail of Tears\" was a result of which United States President's Indian Removal Policy?", "John Quincy Adams", "Martin Van Buren", "Harry S. Truman", "Andrew Jackson", "D", "History", "Easy"),
    ("These two countries held a commonwealth from the 16th to 18th century.", "Hutu and Rwanda", "Poland and Lithuania", "North Korea and South Korea", "Bangladesh and Bhutan", "B", "History", "Easy"),
    ("To what political party did Abraham Lincoln belong when elected POTUS?", "Republican", "Democrat", "Whig", "Independent", "A", "History", "Easy"),
    ("Which of the following ancient peoples was NOT classified as Hellenic (Greek)?", "Illyrians", "Achaeans", "Ionians", "Dorians", "A", "History", "Easy"),
    ("Which one of these countries was NOT in the Central Powers during WWI?", "Turkey", "Austria-Hungary", "Germany", "Spain", "D", "History", "Easy"),
    ("Who was the first ruler of Haiti after the country had gained its independence?", "Henri Christophe", "Alexandre Petion", "Toussaint Louverture", "Jean-Jacques Dessalines", "D", "History", "Easy"),
    ("When is the Ides of March?", "March 14", "March 31", "March 1", "March 15", "D", "History", "Easy"),
    ("Which country was Josef Stalin born in?", "Russia", "Poland", "Georgia", "Germany", "C", "History", "Easy"),
    ("When did the Battle of the Somme begin?", "July 1st, 1916", "July 2nd, 1916", "August 1st, 1916", "June 30th, 1916", "A", "History", "Easy"),
    ("In what year did the nuclear power plant in Chernobyl melt down?", "1975", "1998", "1986", "1991", "C", "History", "Easy"),
    ("In which year did the Invasion of Kuwait by Iraq occur?", "1992", "1990", "1988", "1986", "B", "History", "Easy"),
    ("In which year was Nelson Mandela released from prison", "1980", "1990", "1994", "1992", "B", "History", "Easy"),
    ("The idea of Socialism was articulated and advanced by whom?", "Karl Marx", "Joseph Stalin", "Vladimir Lenin", "Vladimir Putin", "A", "History", "Easy"),
    ("How long did World War II last?", "7 years", "4 years", "5 years", "6 years", "D", "History", "Easy"),
    ("In which country was the Statue of Liberty built and exported to the United States of America?", "France", "England", "Germany", "Spain", "A", "History", "Easy"),
    ("How many Sister Ships were related to the TItanic?", "1", "3", "4", "2", "D", "History", "Easy"),
    ("What does the United States of America celebrate during the 4th of July?", "The anniversary of the Battle of Gettysburg", "The ratification of the Constitution", "The crossing of the Delaware River", "The signing of the Declaration of Independence", "D", "History", "Easy"),
    ("The collapse of the Soviet Union took place in which year?", "1990", "1891", "1992", "1991", "D", "History", "Easy"),
    ("What was the name commonly given to the ancient trade routes that connected the East and West of Eurasia?", "Salt Road", "Spice Road", "Silk Road", "Clay Road", "C", "History", "Easy"),
    ("During the Wars of the Roses (1455 - 1487) which Englishman was dubbed \"the Kingmaker\"?", "Richard Neville", "Richard III", "Thomas Warwick", "Henry V", "A", "History", "Hard"),
    ("In which year did the Tokyo Subway Sarin Attack occur?", "2011", "1995", "2001", "1991", "B", "History", "Hard"),
    ("Who was the last emperor of Mexico?", "Napoleon III", "Agustín de Iturbide", "Ferdinand Maximilian", "Andrés Manuel López Obrador", "C", "History", "Hard"),
    ("What was the real name of the Albanian national leader Skanderbeg?", "Diturak Zhulati", "Iskander Bejko", "Mirash Krasniki", "Gjergj Kastrioti", "D", "History", "Hard"),
    ("What micro-state is considered to have the oldest constitution still in effect?", "Saint Kitts and Nevis", "Andorra", "San Marino", "Monaco", "C", "History", "Hard"),
    ("When was the city of Rome, Italy founded?", "902 BCE", "753 BCE", "524 BCE", "697 BCE", "B", "History", "Hard"),
    ("Who was the President of the United States during the signing of the Gadsden Purchase?", "Abraham Lincoln", "Andrew Johnson", "James Polk", "Franklin Pierce", "D", "History", "Hard"),
    ("Which English king was married to Eleanor of Aquitaine?", "Richard I", "Henry II", "Henry I", "Henry V", "B", "History", "Hard"),
    ("Which country did the Eureka Rebellion, an 1856 battle against colonial rule, take place in?", "Canada", "India", "Australia", "Brazil", "C", "History", "Hard"),
    ("When was Adolf Hitler appointed as Chancellor of Germany?", "February 27, 1933", "October 6, 1939", "September 1, 1939", "January 30, 1933", "D", "History", "Hard"),
    ("When was Finland's 100th year of being independent?", "2018", "2016", "2015", "2017", "D", "History", "Hard"),
    ("List the following Iranic empires in chronological order:", "Achaemenid, Median, Sassanid, Parthian", "Median, Achaemenid, Parthian, Sassanid", "Median, Achaemenid, Sassanid, Parthian", "Achaemenid, Median, Parthian, Sassanid", "B", "History", "Hard"),
    ("What age was King Henry V when he died?", "87", "62", "73", "35", "D", "History", "Hard"),
    ("How many women joined the United States Armed Services during World War II?", "350,000", "500,000", "100,000", "225,000", "A", "History", "Hard"),
    ("Who invented the \"Flying Shuttle\" in 1738; one of the key developments in the industrialization of weaving?", "John Deere", "Richard Arkwright", "James Hargreaves", "John Kay", "D", "History", "Hard"),
    ("What did the abbreviation \"RMS\" stand for in the RMS Titanic in 1912?", "Regular Maritime Schedule ", "Royal Majesty Service", "Royal Mail Ship", "Regulated Maelstrom Sensor", "C", "History", "Hard"),
    ("What was the original name of New York City?", "New London", "New Amsterdam", "New Paris", "New Rome", "B", "History", "Hard"),
    ("When did the French Revolution begin?", "May 05 1789", "April 12 1789", "May 06 1799", "April 05 1789", "A", "History", "Hard"),
    ("Which countries participated in the Lobster War?", "United States and England", "France and Brazil", "Australia and New Zealand", "Canada and Norway", "B", "History", "Hard"),
    ("When did Canada leave the confederation to become their own nation?", "July 1st, 1902", "July 1st, 1832", "July 1st, 1763", "July 1st, 1867", "D", "History", "Hard"),
    ("Which one of these rulers did not belong to the Habsburg dynasty?", "Philip II", "Philip V", "Charles V", "Francis Joseph", "B", "History", "Hard"),
    ("What did the first vending machines in the early 1880's dispense?", "Sodas ", "Alcohol", "Post cards", "Cigarettes", "C", "History", "Hard"),
    ("The main objective of the German operation \"Case Blue\" during World War II was originally to capture what?", "Caucasus", "Crimea", "Stalingrad", "Voronezh", "A", "History", "Hard"),
    ("How long did the Warsaw Uprising during World War II last?", "55 Days", "63 Days", "20 Days", "224 Days", "B", "History", "Hard"),
    ("The Bohemian Revolt (1618-1620) started after Protestants in Prague did what to their Catholic Lords Regents?", "Threw them out of a window", "Hung them.", "Locked them in stockades", "Insulted their mothers", "A", "History", "Hard"),
    ("What was the name of the spy ring that helped the United States win the Revolutionary War?", "Unnamed", "Washington's Spies", "Culper Ring", "New York Spy Ring", "C", "History", "Hard"),
    ("When was the SS or Schutzstaffel established?", "April 4th, 1925", "February 21st, 1926", "March 8th, 1935", "September 1st, 1941", "A", "History", "Hard"),
    ("On which day did ARPANET suffer a 4 hour long network crash?", "November 21, 1969", "October 27, 1980", "December 9, 1991", "October 29, 1969", "B", "History", "Hard"),
    ("What was found in 1946 by two young shepards near a cave?", "Sheep", "Dead Sea Scrolls", "The Blackbeard Chest", "The First Oaxaca Cave Sleeper", "B", "History", "Hard"),
    ("Who assassinated President James A. Garfield?", "Leon Czolgosz", "John Wilkes Booth", "Charles Guiteau", "Sirhan Sirhan", "C", "History", "Hard"),
    ("In addition to his career as an astrologer and \"prophet\", Nostradamus published a 1555 treatise that included a section on what?", "Teaching parrots to talk", "Digging graves", "Cheating at card games", "Making jams and jellies", "D", "History", "Hard"),
    ("Where was Napoleon Bonaparte born?", "Normandy", "Paris", "Brittany", "Corsica", "D", "History", "Hard"),
    ("What Southeast Asian country was formerly known as 'Lan Xang'?", "Vietnam", "Cambodia", "Thailand", "Laos", "D", "History", "Hard"),
    ("The coat of arms of the King of Spain contains the arms from the monarchs of Castille, Leon, Aragon and which other former Iberian kingdom?", "Granada", "Catalonia", "Galicia", "Navarre", "D", "History", "Hard"),
    ("The Battle of Hastings was fought in which year?", "1420", "1066", "911", "1204", "B", "History", "Hard"),
    ("Which of these theoretical phycisists first predicted the existence of antimatter?", "Albert Einstein", "Werner Heisenberg", "Paul Dirac", "Niels Bohr", "C", "History", "Hard"),
    ("When did Spanish Peninsular War start?", "1809", "1808", "1806", "1810", "B", "History", "Hard"),
    ("What was the name of the German offensive operation in October 1941 to take Moscow before winter?", "Operation Barbarossa", "Operation Typhoon", "Case Blue", "Operation Sunflower", "B", "History", "Hard"),
    ("Which of these positions did the astronomer and physicist Isaac Newton not hold?", "Professor of Mathematics", "Warden of the Royal Mint", "Surveyor to the City of London", "Member of Parliament", "C", "History", "Hard"),
    ("During World War I, which nation's monarchs were blood related?", "Serbia, Russia, Croatia", "Germany, Spain, Austria", "England, Germany, Russia", "France, Russia, Germany", "C", "History", "Hard"),
    ("Bohdan Khmelnytsky was which of the following?", "General Secretary of the Communist Party of the USSR", "Prince of Wallachia", "Leader of the Ukrainian Cossacks", "Grand Prince of Novgorod", "C", "History", "Hard"),
    ("What is the name of the Boeing B-29 that dropped the 'Little Boy' atomic bomb on Hiroshima?", "Necessary Evil", "Enola Gay", "Full House", "The Great Artiste", "B", "History", "Hard"),
    ("What year was Canada founded in?", "1668", "1867", "1798", "1859", "B", "History", "Hard"),
    ("Which King of England was faced with the Peasants' Revolt in 1381?", "Edward II", "Henry IV", "Richard II", "Edward III", "C", "History", "Hard"),
    ("The pantheon in Rome was used to worship what god?", "Both Athena and Zeus", "Any god they wanted", "Athena", "Zeus", "B", "History", "Hard"),
    ("During the Roman Triumvirate of 42 BCE, what region of the Roman Republic was given to Lepidus?", "Hispania ", "Italia", "Gallia", "Asia", "A", "History", "Hard"),
    ("Pianist Frédéric Chopin was a composer of which musical era?", "Baroque", "Renaissance", "Romantic", "Classic", "C", "History", "Hard"),
    ("What was the code name for the Allied invasion of Southern France on August 15th, 1944?", "Operation Torch", "Operation Market Garden", "Operation Dragoon", "Operation Overlord", "C", "History", "Hard"),
    ("Which of the following was not one of Joseph Stalin's ten blows during World War II?", "Crimean Offensive", "Leningrad-Novgorod Offensive", "Operation Bagration", "Vistula-Oder Offensive", "D", "History", "Hard"),
    ("The Hagia Sophia was commissioned by which emperor of the Byzantine Empire?", "Constantine IV", "Theodosius the Great", "Arcadius", "Justinian I", "D", "History", "Hard"),
    ("In the 2014 FIFA World Cup, what was the final score in the match Brazil - Germany?", "1-5", "2-6", "1-7", "1-6", "C", "Sports", "Easy"),
    ("How many points did LeBron James score in his first NBA game?", "19", "69", "41", "25", "D", "Sports", "Easy"),
    ("\"Stadium of Light\" is the home stadium for which soccer team?", "Sunderland FC", "Manchester United", "Barcelona FC", "Paris Saints-Germain", "A", "Sports", "Easy"),
    ("In golf, what name is given to a hole score of two under par?", "Albatross", "Bogey", "Birdie", "Eagle", "D", "Sports", "Easy"),
    ("Which team won 2014 FIFA World Cup in Brazil?", "Argentina", "Germany", "Netherlands", "Brazil", "B", "Sports", "Easy"),
    ("Which African American is in part responsible for integrating  Major League baseball?", "Satchell Paige", "Curt Flood", "Jackie Robinson", "Roy Campanella", "C", "Sports", "Easy"),
    ("Which country hosted the 2020 Summer Olympics?", "China", "Germany", "Japan", "Australia", "C", "Sports", "Easy"),
    ("Which of these teams has Jaromir Jagr not played for?", "New York Islanders", "Dallas Stars", "New Jersey Devils", "Calgary Flames", "A", "Sports", "Easy"),
    ("What year did the New Orleans Saints win the Super Bowl?", "2011", "2009", "2010", "2008", "C", "Sports", "Easy"),
    ("What was the year of estabilishment of the Bari Italian Football Club?", "2014", "1895", "1945", "1908", "D", "Sports", "Easy"),
    ("Who won the 2015 Formula 1 World Championship?", "Sebastian Vettel", "Jenson Button", "Lewis Hamilton", "Nico Rosberg", "C", "Sports", "Easy"),
    ("What was the final score of the Germany vs. Brazil 2014 FIFA World Cup match?", "7 - 1", "0 - 1", "16 - 0", "3 - 4", "A", "Sports", "Easy"),
    ("Which English football club has the nickname 'The Foxes'?", "Bradford City", "Northampton Town", "West Bromwich Albion", "Leicester City", "D", "Sports", "Easy"),
    ("When was the first official international game played?", "1880", "1872", "1863", "1865", "B", "Sports", "Easy"),
    ("How many players are there in an association football/soccer team?", "8", "9", "11", "10", "C", "Sports", "Easy"),
    ("What national team won the first UEFA Nations League?", "England", "Netherlands", "Switzerland", "Portugal", "D", "Sports", "Easy"),
    ("Which of these NHL teams originally played in Atlanta?", "St. Louis Blues", "Vancouver Canucks", "Minnesota Wild", "Calgary Flames", "D", "Sports", "Easy"),
    ("Which wrestler won the 2019 Men’s Royal Rumble?", "Braun Strowman", "AJ Styles", "Seth Rollins", "Andrade", "C", "Sports", "Easy"),
    ("What is the most common type of pitch thrown by pitchers in baseball?", "Slowball", "Palmball", "Screwball", "Fastball", "D", "Sports", "Easy"),
    ("Who did Steven Gerrard win the Champions League with?", "Chelsea", "Man City", "Real Madrid", "Liverpool", "D", "Sports", "Easy"),
    ("Who won the UEFA Champions League in 2017?", "Juventus F.C.", "Real Madrid C.F.", "AS Monaco FC", "Atletico Madrid", "B", "Sports", "Easy"),
    ("Which country hosted the 2018 FIFA World Cup?", "United States", "Russia", "Saudi Arabia", "Germany", "B", "Sports", "Easy"),
    ("Which country won the 2018 FIFA World Cup hosted in Russia?", "Belgium", "France", "Croatia", "England", "B", "Sports", "Easy"),
    ("What team won the 2016 MLS Cup?", "Montreal Impact", "Toronto FC", "Colorado Rapids", "Seattle Sounders", "D", "Sports", "Easy"),
    ("Which of the following sports is not part of the triathlon?", "Horse-Riding", "Running", "Swimming", "Cycling", "A", "Sports", "Easy"),
    ("Which player holds the NHL record of 2,857 points?", "Wayne Gretzky", "Sidney Crosby", "Gordie Howe", "Mario Lemieux ", "A", "Sports", "Easy"),
    ("Which NFL team plays for New England?", "Dolphins", "Chiefs", "Patriots", "49ers", "C", "Sports", "Easy"),
    ("Which team won the 2015-16 English Premier League?", "Liverpool", "Manchester United", "Cheslea", "Leicester City", "D", "Sports", "Easy"),
    ("What sport features the terms love, deuce, match and volley?", "Tennis", "Cricket", "Basketball", "Curling", "A", "Sports", "Easy"),
    ("Which city did the former NHL team \"The Nordiques\" originiate from?", "New York", "Montreal", "Houston", "Quebec City", "D", "Sports", "Easy"),
    ("The Los Angeles Dodgers were originally from what U.S. city?", "Brooklyn", "Seattle", "Las Vegas", "Boston", "A", "Sports", "Easy"),
    ("Which country produced football players such as Cafu, Roberto Carlos and Pelé?", "Spain", "Argentina", "Portugal", "Brazil", "D", "Sports", "Easy"),
    ("Which year did Jenson Button won his first ever Formula One World Drivers' Championship?", "2009", "2010", "2007", "2006", "A", "Sports", "Easy"),
    ("When was the FC Schalke 04 founded?", "1909", "2008", "1999", "1904", "D", "Sports", "Easy"),
    ("In what sport is a \"shuttlecock\" used?", "Cricket", "Table Tennis", "Rugby", "Badminton", "D", "Sports", "Easy"),
    ("What is the name of Manchester United's home stadium?", "St James Park", "Anfield", "City of Manchester Stadium", "Old Trafford", "D", "Sports", "Easy"),
    ("In baseball, how many fouls are an out?", "5", "2", "0", "3", "C", "Sports", "Easy"),
    ("Which two teams played in Super Bowl XLII?", "The Seattle Seahawks & The Denver Broncos", "The Philadelphia Eagles & The New England Patriots", "The New York Giants & The New England Patriots", "The Green Bay Packers & The Pittsburgh Steelers", "C", "Sports", "Easy"),
    ("Which country hosted the 2022 FIFA World Cup?", "Qatar", "Switzerland", "Japan", "USA", "A", "Sports", "Easy"),
    ("Which team has won the most Stanley Cups in the NHL?", "Chicago Blackhawks", "Toronto Maple Leafs", "Montreal Canadians", "Detroit Red Wings", "C", "Sports", "Easy"),
    ("Who won the 2016 Formula 1 World Driver's Championship?", "Nico Rosberg", "Max Verstappen", "Kimi Raikkonen", "Lewis Hamilton", "A", "Sports", "Easy"),
    ("In Baseball, how many times does the ball have to be pitched outside of the strike zone before the batter is walked?", "2", "3", "1", "4", "D", "Sports", "Easy"),
    ("Who won the UEFA Champions League in 2016?", "FC Bayern Munich", "Manchester City F.C.", "Atletico Madrid", "Real Madrid C.F.", "D", "Sports", "Easy"),
    ("Which boxer was banned for taking a bite out of Evander Holyfield's ear in 1997?", "Roy Jones Jr.", "Lennox Lewis", "Evander Holyfield", "Mike Tyson", "D", "Sports", "Easy"),
    ("Who is often called \"the Maestro\" in the men's tennis circuit?", "Boris Becker", "Roger Federer", "Pete Sampras", "Bill Tilden", "B", "Sports", "Easy"),
    ("The Rio 2016 Summer Olympics held it's closing ceremony on what date?", "August 19", "August 23", "August 21", "August 17", "C", "Sports", "Easy"),
    ("How many soccer players should be on the field at the same time?", "24", "26", "22", "20", "C", "Sports", "Easy"),
    ("This Canadian television sportscaster is known for his \"Hockey Night in Canada\" role, a commentary show during hockey games.", "Don Taylor ", "Donald Sutherland", "Don McKellar", "Don Cherry", "D", "Sports", "Easy"),
    ("Who won the 2017 Formula One World Drivers' Championship?", "Max Verstappen", "Sebastian Vettel", "Nico Rosberg", "Lewis Hamilton", "D", "Sports", "Easy"),
    ("Who won the premier league title in the 2015-2016 season following a fairy tale run?", "Leicester City", "Tottenham Hotspur", "Stoke City", "Watford", "A", "Sports", "Easy"),
    ("How many colors are there in a rainbow?", "8", "7", "10", "9", "B", "General Knowledge", "Easy"),
    ("In \"Shrek\", what comedic actor voices Donkey?", "Chris Rock", "Bernie Mac", "Richard Pryor", "Eddie Murphy", "D", "General Knowledge", "Easy"),
    ("Why is the night sky dark? ", "Dust clouds absorb light ", "Redshift doesn't let us see distant stars ", "Quantum mechanics", "The universe is finite in age and size", "D", "General Knowledge", "Easy"),
    ("How tall is the Burj Khalifa?", "2,717 ft", "2,722 ft", "2,546 ft", "3,024 ft", "B", "General Knowledge", "Easy"),
    ("What was the name of Sqiudward's bad painting in the Spongebob episode \"Artist Unknown?\"", "Bold and Brash", "Squidward en Repose", "Rippy Bits", "Tilted Perspectives", "A", "General Knowledge", "Easy"),
    ("Which best selling toy of 1983 caused hysteria, resulting in riots breaking out in stores?", "Care Bears", "Rubik’s Cube", "Transformers", "Cabbage Patch Kids", "D", "General Knowledge", "Easy"),
    ("In DC comics where does the Green Arrow (Oliver Queen) live?", "Metropolis", "Gotham City", "Star City", "Central City", "C", "General Knowledge", "Easy"),
    ("Which of the following is the IATA code for Manchester Airport?", "EGLL", "EGCC", "MAN", "LHR", "C", "General Knowledge", "Easy"),
    ("How would one say goodbye in Spanish?", " Hola", "Adiós", "Au Revoir", "Salir", "B", "General Knowledge", "Easy"),
    ("Which of these words refers to something made, distributed, or sold illegally?", "Bootstrap", "Bootlace", "Bootleg", "Bootblack", "C", "General Knowledge", "Easy"),
    ("What is the first book of the Old Testament?", "Leviticus", "Exodus", "Genesis", "Numbers", "C", "General Knowledge", "Easy"),
    ("How many syllables make up a haiku?", "17", "15", "21", "10", "A", "General Knowledge", "Easy"),
    ("Which of these Marvel games was released on the Playstation 2?", "Wolverine: Adamantium Rage", "Silver Surfer", "Spider-Man 2", "Howard the Duck", "C", "General Knowledge", "Easy"),
    ("What is the currency of India and Pakistan as well as a few other Asian countries?", "Dinar", "Peso", "Riyal", "Rupee", "D", "General Knowledge", "Easy"),
    ("The drug cartel run by Pablo Escobar originated in which South American city?", "Cali", "Medellín", "Quito", "Bogotá", "B", "General Knowledge", "Easy"),
    ("What country does sushi & karaoke come from?", "Vietnam", "China", "Japan", "South Korea", "C", "General Knowledge", "Easy"),
    ("What is the famous Papa John's last name?", "Schnatter", "ANDERSON", "Chowder", "Williams", "A", "General Knowledge", "Easy"),
    ("The Canadian $1 coin is colloquially known as a what?", "Foolie", "Moodie", "Loonie", "Boolie", "C", "General Knowledge", "Easy"),
    ("Who is considered the \"Father of Modern Philosophy\"?", "Antoine Lavoiser", "Albert Einstein", "René Descartes", "Plato", "C", "General Knowledge", "Easy"),
    (" Which chemical element, number 11 in the Periodic table, has the symbol Na?", "Sodium", "Lead", "Carbon", "Nitrogen", "A", "General Knowledge", "Easy"),
    ("What do sailors call the front of a boat?", "Port", "Stern", "Bow", "Starboard", "C", "General Knowledge", "Easy"),
    ("Who is the author of Jurassic Park?", "Chuck Paluhniuk", "Michael Crichton", "Peter Benchley", "Irvine Welsh", "B", "General Knowledge", "Easy"),
    ("If you are caught \"Goldbricking\", what are you doing wrong?", "Slacking", "Smoking", "Stealing", "Cheating", "A", "General Knowledge", "Easy"),
    ("Which canal connects the Mediterranean Sea with the Red Sea?", "Qaraqum Canal", "Sinai Canal", "Suez Canal", "Panama Canal", "C", "General Knowledge", "Easy"),
    ("Which of these holidays is NOT usually celebrated in the month of December?", "Hanukkah", "Thanksgiving", "Kwanzaa", "Christmas", "B", "General Knowledge", "Easy"),
    ("What is the French word for \"hat\"?", "Bonnet", " Casque", "Chapeau", " Écharpe", "C", "General Knowledge", "Easy"),
    ("Which of the following card games revolves around numbers and basic math?", "Twister", "Go Fish", "Munchkin", "Uno", "D", "General Knowledge", "Easy"),
    ("What was the nickname given to the Hughes H-4 Hercules, a heavy transport flying boat which achieved flight in 1947?", "Trojan Horse", "Spruce Goose", "Noah's Ark", "Fat Man", "B", "General Knowledge", "Easy"),
    ("Virgin Trains, Virgin Atlantic and Virgin Racing, are all companies owned by which famous entrepreneur?   ", "Donald Trump", "Alan Sugar", "Richard Branson", "Bill Gates", "C", "General Knowledge", "Easy"),
    ("Which one of these is not a typical European sword design?", "Scimitar", "Ulfberht", "Falchion", "Flamberge", "A", "General Knowledge", "Easy"),
    ("The New York Times slogan is, “All the News That’s Fit to…”", "Print", "Look", "Digest", "Read", "A", "General Knowledge", "Easy"),
    ("Which country has the Union Jack in its flag?", "Canada", "South Africa", "New Zealand", "Hong Kong", "C", "General Knowledge", "Easy"),
    ("What is the name of NASA’s most famous space telescope?", "Millenium Falcon", "Hubble Space Telescope", "Big Eye", "Death Star", "B", "General Knowledge", "Easy"),
    ("In a standard Gregorian calendar, how many months begin with the letter 'J'?", "Three", "Five", "Two", "Four", "A", "General Knowledge", "Easy"),
    ("What is the name of the extra pedal on a manual or standard transmission car?", "Clutch", "Booster", "Parking Brake", "Shifter", "A", "General Knowledge", "Easy"),
    ("Earth is located in which galaxy?", "The Milky Way Galaxy", "The Galaxy Note", "The Black Hole", "The Mars Galaxy", "A", "General Knowledge", "Easy"),
    ("What company owns Outlook?", "Yahoo", "Microsoft", "Apple", "Google", "B", "General Knowledge", "Easy"),
    ("Trypophobia is the fear of ", "groups of holes", "public speaking", "eating too much", "swimming in deep water", "A", "General Knowledge", "Easy"),
    ("In which fast food chain can you order a Jamocha Shake?", "Wendy's", "Arby's", "McDonald's", "Burger King", "B", "General Knowledge", "Easy"),
    ("Who is the origin of the quote \"What doesn't kill you makes you stronger\"?", "Kelly Clarkson", "Friedrich Nietzsche", "Christopher Hitchens", " G. Gordon Liddy", "B", "General Knowledge", "Easy"),
    ("What kind of aircraft was developed by Igor Sikorsky in the United States in 1942?", "Jet", "Helicopter", "Space Capsule", "Stealth Blimp", "B", "General Knowledge", "Easy"),
    ("Which American-owned brewery led the country in sales by volume in 2015?", "Boston Beer Company", "Anheuser Busch", "D. G. Yuengling and Son, Inc", "Miller Coors", "C", "General Knowledge", "Easy"),
    ("What is Cynophobia the fear of?", "Dogs", "Birds", "Flying", "Germs", "A", "General Knowledge", "Easy"),
    ("How many letters are there in the English alphabet?", "24", "23", "28", "26", "D", "General Knowledge", "Easy"),
    ("What is the perimeter of a circle more commonly known as?", "Radius", "Circumference", "Diameter", "Arc", "B", "General Knowledge", "Easy"),
    ("Antibiotics are generally taken to combat what?", "Bacterial infections", "Viruses", "Muscular pains", "Migraines", "A", "General Knowledge", "Easy"),
    ("What is the full meaning of RAM?", "Random Assist Memory", "Rand Assist Mandate", "Ram", "Random Access Memory", "D", "General Knowledge", "Easy"),
    ("Which type of cutlery is most suited for eating soup?", "Chopsticks", "Fork", "Spoon", "Knife", "C", "General Knowledge", "Easy"),
    ("What is the French word for \"fish\"?", "poisson", "fiche", "mer", "escargot", "A", "General Knowledge", "Easy"),
    ("Which country developed the AK-47 assault rifle?", "Poland", "Israel", "Soviet Union", "Iran", "C", "General Knowledge", "Easy"),
    ("If you planted the seeds of Quercus robur, what would grow?", "Flowers", "Vegetables", "Grains", "Trees", "D", "General Knowledge", "Hard"),
    ("What is the name of the currency used in Ethiopia?", "Rand", "Birr", "Dirham", "U.S. Dollar", "B", "General Knowledge", "Hard"),
    ("In \"Resident Evil 3\", how many inventory slots does Jill have at the start of the game?", "6", "10", "12", "8", "D", "General Knowledge", "Hard"),
    ("Xanthophobia is the fear of what color?", "Yellow", "Green", "Red", "Blue", "A", "General Knowledge", "Hard"),
    ("According to the 2014-2015 Australian Bureau of Statistics, what percentage of Australians were born overseas?", "7%", "28%", "20%", "13%", "B", "General Knowledge", "Hard"),
    ("The word \"astasia\" means which of the following?", "The inability to make decisions", "A feverish desire to rip one's clothes off", "The inability to stand up", "The inability to concentrate on anything", "C", "General Knowledge", "Hard"),
    ("Originally another word for poppy, coquelicot is a shade of what?", "Pink", "Blue", "Red", "Green", "C", "General Knowledge", "Hard"),
    ("What is the weight of a Gold Bar in Fallout: New Vegas?", "32.50 Pounds", "30 Pounds", "35 Pounds", "40 Pounds", "C", "General Knowledge", "Hard"),
    ("Who founded the Khan Academy?", "Adel Khan", "Sal Khan", "Ben Khan", "Kitt Khan", "B", "General Knowledge", "Hard"),
    ("This Ghanaian entrepreneur is a pioneer of microlending.", "Sionne Neely", "Ama Ata Aido", "Farida Bedwei", "Esther Afua Ocloo", "D", "General Knowledge", "Hard"),
    ("Where is Apple Inc. headquartered?", "Cupertino, California", "Redwood City, California", "Redmond, Washington", "Santa Monica, CA", "A", "General Knowledge", "Hard"),
    ("Going by the International Code of Signals, which single flag is interpreted as \"I require assistance (not distress)\"?", "Delta", "Victor", "Kilo", "Papa", "B", "General Knowledge", "Hard"),
    ("In flight systems, what does the initialism \"TCAS\" stand for?", "Traffic Call-sign Abbreviation System", "Traffic Configuration Alignment System", "Traffic Collision Avoidance System", "Traffic Communication Alert System", "C", "General Knowledge", "Hard"),
    ("Which of the following languages does NOT use gender as a part of its grammar?", "Danish", "German", "Polish", "Turkish", "D", "General Knowledge", "Hard"),
    ("What is the most commonly used noun in the English language?", "Water", "Time", "Home", "Man", "B", "General Knowledge", "Hard"),
    ("What is the airspeed velocity of an unladen swallow?", "24 MPH", "15 MPH", "200 MPH", "20 MPH", "A", "General Knowledge", "Hard"),
    ("\"Nephelococcygia\" is the practice of doing what? ", "Swimming in freezing water", "Sleeping with your eyes open", "Breaking glass with your voice", "Finding shapes in clouds", "D", "General Knowledge", "Hard"),
    ("According to Fair Works Australia, how long do you have to work to get Long Service Leave?", "6 months", "7 years", "8 years", "2 years", "B", "General Knowledge", "Hard"),
    ("De Eemhof, Port Zelande and Het Heijderbos are holiday villas owned by what company?", "Keycamp", "Yelloh Village", "Center Parcs", "Villa Plus", "C", "General Knowledge", "Hard"),
    ("Nephelococcygia is the practice of doing what?", "Swimming in freezing water", "Breaking glass with your voice", "Sleeping with your eyes open", "Finding shapes in clouds", "D", "General Knowledge", "Hard"),
    ("In the MMO RPG \"Realm of the Mad God\", what dungeon is widely considered to be the most difficult?", "The Tomb of the Acient's", "The Shatter's", "The Puppet Master's Theater", "Snake Pit", "B", "General Knowledge", "Hard"),
    ("Which of these Indian languages is not part of the Indo-European language family?", "Tamil", "Urdu", "Hindi", "Punjabi", "A", "General Knowledge", "Hard"),
    ("The Swedish word \"Grunka\" means what in English?", "People", "Pineapple", "Thing", "Place", "C", "General Knowledge", "Hard"),
    ("Chartreuse is a color between yellow and what?", "Green", "Purple", "Red", "Black", "A", "General Knowledge", "Hard"),
    ("Sciophobia is the fear of what?", "Shadows", "Eating", "Transportation", "Bright lights", "A", "General Knowledge", "Hard"),
    ("How many calories are in a 355 ml can of Pepsi Cola?", "155", "150", "200", "100", "B", "General Knowledge", "Hard"),
    ("In linguistics, which of the following is not one of the Gricean Maxims under the Cooperative Principal?", "Length", "Quality", "Manner", "Relation", "A", "General Knowledge", "Hard"),
    ("The Quadrangularis Reversum is best described as which of the following?", "A building in Oxford University", "A geometric theorem", "A percussion instrument", "A chess move", "C", "General Knowledge", "Hard"),
    ("What year was the RoboSapien toy robot released?", "2001", "2006", "2004", "2000", "C", "General Knowledge", "Hard"),
    ("Which product did Nokia, the telecommunications company, originally sell?", "Paper", "Phones", "Computers", "Processors", "A", "General Knowledge", "Hard"),
    ("Which church's interior in Vatican City was designed in 1503 by renaissance architects including Bramante, Michelangelo and Bernini?", "St. Mark’s Basilica", "Catania Cathedral", "The Duomo of Florence", "St. Peter's Basilica", "D", "General Knowledge", "Hard"),
    ("Virtual reality company Oculus VR lost which of it's co-founders in a freak car accident in 2013?", "Nate Mitchell", "Jack McCauley", "Palmer Luckey", "Andrew Scott Reisse", "D", "General Knowledge", "Hard"),
    ("If someone said \"you are olid\", what would they mean?", "You are incomprehensible/an idiot.", "Your appearance is repulsive.", "You smell extremely unpleasant.", "You are out of shape/weak.", "C", "General Knowledge", "Hard"),
    ("What is the romanized Chinese word for \"airplane\"?", "Zongxian", "Qiche", "Feiji", "Huojian", "C", "General Knowledge", "Hard"),
    ("Located in Chile, El Teniente is the world's largest underground mine for what metal?", "Silver", "Copper", "Iron", "Nickel", "B", "General Knowledge", "Hard"),
    ("Where in La Coruña (Spain) is the headquarters of \"Inditex\", the biggest fashion group in the world?", "Arteijo", "Mugía", "Sanjenjo", "Órdenes", "A", "General Knowledge", "Hard"),
    ("In \"Battle Cats\", what is Moneko / MISS Moneko's critical percentage rate?", "25%", "20%", "10%", "15%", "D", "General Knowledge", "Hard"),
    ("What is the romanized Arabic word for \"moon\"?", "Shams", "Najma", "Qamar", "Kawkab", "C", "General Knowledge", "Hard"),
    ("The words \"bungalow\" and \"shampoo\" originate from the languages of which country?", "Papua New Guinea", "India", "China", "Ethiopia", "B", "General Knowledge", "Hard"),
    ("What was the third country to have a McDonald's restaurant?", "France", "Japan", "Australia", "Costa Rica", "D", "General Knowledge", "Hard"),
    ("What was Bank of America originally established as?", "Bank of Long Island", "Bank of Pennsylvania", "Bank of Italy", "Bank of Charlotte", "C", "General Knowledge", "Hard"),
    ("The word \"abulia\" means which of the following?", "The inability to concentrate on anything", "The inability to stand up", "The inability to make decisions", "A feverish desire to rip one's clothes off", "C", "General Knowledge", "Hard"),
    ("What type of dog is 'Handsome Dan', the mascot of Yale University?", "Bulldog", "Yorkshire Terrier", "Pug", "Boxer", "A", "General Knowledge", "Hard"),
    ("To which language family does Kazakh belong?", "Turkic", "Mongolic", "Uralic", "Indo-European", "A", "General Knowledge", "Hard"),
    ("How many notes are there on a standard grand piano?", "108", "88", "98", "78", "B", "General Knowledge", "Hard"),
    ("Which of the following is an existing family in \"The Sims\"?", "The Proud Family", "The Simoleon Family", "The Goth Family", "The Family", "C", "General Knowledge", "Hard"),
    ("Disney's Haunted Mansion is home to a trio of Hitchhiking Ghosts. Which of these is NOT one of them?", "Phineas", "Gus", "Ezra", "Harry", "D", "General Knowledge", "Hard"),
    ("Which one of these Swedish companies was founded in 1943?", "H & M", "Lindex", "Clas Ohlson", "IKEA", "D", "General Knowledge", "Hard"),
    ("What is the romanized Korean word for \"heart\"?", "Aejeong", "Segseu", "Jeongsin", "Simjang", "D", "General Knowledge", "Hard"),
    ("Which of these banks are NOT authorized to issue currency notes in Hong Kong?", "HSBC", "Standard Chartered", "Bank of China", "OCBC", "D", "General Knowledge", "Hard"),
]
